### ISSUE TITLE
Java-script letter toggling

### ISSUE THREAD

**Issue by aburrell** [EquitableLettersSP/ELSP#14]
Eventually, it would be nice to have a java-script routine that allows people to toggle names and genders in the example letters.  This would allow people to consider how a names gender and ethnicity affect their impression of the text.

**Comment by johncoxon** [comment]
Do any of us have the expertise to do this? If not, we might want to recruit?

**Comment by katieefrey** [comment]
I saw Angeline's presentation at TESS this morning and I started work on implementing some suggested updates, including this, in Pull Request #63 

I'm pretty happy with how its turned out, but I only implemented it on the first paragraph of the first letter (and incompletely on the first paragraph of the second letter).
As I mention in the pull request itself, I think there should be some styling changes made to the pronoun selector, but if you are happy with the way the pronouns change throughout the letter, then we can probably move forward with tagging all pronouns, etc in the letters.
